# Generated by Django 5.1.4 on 2024-12-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "CASH"), ("transfer", "TRANSFER")],
                max_length=20,
                verbose_name="TYPE OF PAYMENT",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Upload your photo",
                null=True,
                upload_to="users/avatars/",
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Enter your email address",
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
        ),
    ]
