# Generated by Django 5.1.4 on 2024-12-11 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Choose a course",
                        max_length=100,
                        verbose_name="name of the course",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="course_previews/"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Choose a course",
                        null=True,
                        verbose_name="name of the course",
                    ),
                ),
            ],
            options={
                "verbose_name": "course",
                "verbose_name_plural": "courses",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Choose a lesson",
                        null=True,
                        verbose_name="description of the lesson",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="lesson_previews/"
                    ),
                ),
                ("video_url", models.URLField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="lms.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "lesson",
                "verbose_name_plural": "lessons",
            },
        ),
    ]
