# Generated by Django 5.1.4 on 2024-12-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Provide a lesson description",
                null=True,
                verbose_name="description of the lesson",
            ),
        ),
    ]
