# Generated by Django 5.1.4 on 2024-12-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_alter_lesson_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="name",
        ),
        migrations.AddField(
            model_name="course",
            name="title",
            field=models.CharField(default=1, max_length=255, verbose_name="Title"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Provide a description for the course",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="course_previews/",
                verbose_name="Preview",
            ),
        ),
    ]
